use regex::Regex;

pub fn mysql_to_postgres(source: &str) -> String {
    let mut result = source.to_string();

    let re = Regex::new(r"`([^`]+)`").unwrap();
    result = re.replace_all(&result, "\"$1\"").to_string();

    let re = Regex::new(r",?\s*ENGINE\s*=\s*\w+(?:\s+DEFAULT\s+CHARSET\s*=\s*\w+(?:\s+COLLATE\s*=\s*\w+)?)?").unwrap();
    result = re.replace_all(&result, "").to_string();
    let re = Regex::new(r"\s+ENGINE\s*=\s*\w+(?:\s+DEFAULT\s+CHARSET\s*=\s*\w+(?:\s+COLLATE\s*=\s*\w+)?)?").unwrap();
    result = re.replace_all(&result, "").to_string();

    let re = Regex::new(r"\bINT\b\s*AUTO_INCREMENT").unwrap();
    result = re.replace_all(&result, "SERIAL").to_string();
    let re = Regex::new(r"\bBIGINT\b\s*AUTO_INCREMENT").unwrap();
    result = re.replace_all(&result, "BIGSERIAL").to_string();
    let re = Regex::new(r"\bSMALLINT\b\s*AUTO_INCREMENT").unwrap();
    result = re.replace_all(&result, "SMALLSERIAL").to_string();
    let re = Regex::new(r"AUTO_INCREMENT").unwrap();
    result = re.replace_all(&result, "GENERATED BY DEFAULT AS IDENTITY").to_string();

    let re = Regex::new(r"\bTINYINT\s*\(1\)").unwrap();
    result = re.replace_all(&result, "BOOLEAN").to_string();
    let re = Regex::new(r"\bTINYINT\b").unwrap();
    result = re.replace_all(&result, "SMALLINT").to_string();
    let re = Regex::new(r"\bINT\s*\(\d+\)").unwrap();
    result = re.replace_all(&result, "INTEGER").to_string();
    let re = Regex::new(r"\bINT\b").unwrap();
    result = re.replace_all(&result, "INTEGER").to_string();
    let re = Regex::new(r"\bDATETIME\b").unwrap();
    result = re.replace_all(&result, "TIMESTAMP").to_string();
    let re = Regex::new(r"\bBLOB\b").unwrap();
    result = re.replace_all(&result, "BYTEA").to_string();
    let re = Regex::new(r"\bLONGBLOB\b").unwrap();
    result = re.replace_all(&result, "BYTEA").to_string();
    let re = Regex::new(r"\bMEDIUMBLOB\b").unwrap();
    result = re.replace_all(&result, "BYTEA").to_string();
    let re = Regex::new(r"\bTINYBLOB\b").unwrap();
    result = re.replace_all(&result, "BYTEA").to_string();
    let re = Regex::new(r"\bMEDIUMTEXT\b").unwrap();
    result = re.replace_all(&result, "TEXT").to_string();
    let re = Regex::new(r"\bLONGTEXT\b").unwrap();
    result = re.replace_all(&result, "TEXT").to_string();
    let re = Regex::new(r"\bTINYTEXT\b").unwrap();
    result = re.replace_all(&result, "TEXT").to_string();
    let re = Regex::new(r"\bDOUBLE\b").unwrap();
    result = re.replace_all(&result, "DOUBLE PRECISION").to_string();
    let re = Regex::new(r"\bFLOAT\b").unwrap();
    result = re.replace_all(&result, "REAL").to_string();

    let re = Regex::new(r"\s+UNSIGNED\b").unwrap();
    result = re.replace_all(&result, "").to_string();

    let re = Regex::new(r"\bIFNULL\s*\(").unwrap();
    result = re.replace_all(&result, "COALESCE(").to_string();

    let re = Regex::new(r"INSERT\s+IGNORE\s+INTO").unwrap();
    result = re.replace_all(&result, "INSERT INTO").to_string();
    let re = Regex::new(r"INSERT\s+INTO\s+(\w+)\s+VALUES\s*(.*)").unwrap();
    result = re.replace_all(&result, |caps: &regex::Captures| {
        format!("INSERT INTO {} VALUES {} ON CONFLICT DO NOTHING", &caps[1], &caps[2])
    }).to_string();

    let re = Regex::new(r"REPLACE\s+INTO").unwrap();
    result = re.replace_all(&result, "INSERT INTO").to_string();

    let re = Regex::new(r"ON\s+DUPLICATE\s+KEY\s+UPDATE").unwrap();
    result = re.replace_all(&result, "ON CONFLICT DO UPDATE").to_string();

    let re = Regex::new(r"\bLIKE\b").unwrap();
    result = re.replace_all(&result, "ILIKE").to_string();

    let re = Regex::new(r"(GROUP\s+BY\s+\d+)").unwrap();
    result = re.replace_all(&result, "$1 /* PG: replace numeric with column names */").to_string();

    let re = Regex::new(r"SHOW\s+TABLES").unwrap();
    result = re.replace_all(&result, "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'").to_string();

    let re = Regex::new(r"SHOW\s+DATABASES").unwrap();
    result = re.replace_all(&result, "SELECT datname FROM pg_database").to_string();

    let re = Regex::new(r"DESCRIBE\s+(\w+)").unwrap();
    result = re.replace_all(&result, "SELECT column_name, data_type FROM information_schema.columns WHERE table_name = '$1'").to_string();

    let re = Regex::new(r"USE\s+(\w+);?").unwrap();
    result = re.replace_all(&result, "-- Connected to database: $1 (PG: connection set at session level)").to_string();

    let re = Regex::new(r"\s+COLLATE\s+\w+").unwrap();
    result = re.replace_all(&result, "").to_string();

    let re = Regex::new(r"\s+CHARACTER\s+SET\s+\w+").unwrap();
    result = re.replace_all(&result, "").to_string();

    result
}
